### ISSUE TITLE
Zoom only the content, not the toolbar, for the built-in PDF viewer

### ISSUE THREAD

**Issue by struq** [haxiomic/firefox-multi-touch-zoom#4] opened 2017-12-08 23:50 UTC
Hi haxiomic,
When viewing a PDF in Firefox, multi-touch zoom provided by this addon is affecting the whole page including the toolbar and sidebar. It might be better if only the PDF content is zoomed, similar to the behavior when using Cmd+ or Cmd- keyboard shortcuts.

**Comment by haxiomic** [comment] 2017-12-09 07:34
Thanks for the suggestion @struq, I agree. I've just tried some experiments and it is possible to use the PDF viewer's zoom % to manage scaling. There's some tricky bits involved so it'll take some time but I'm keen have it as a feature.

Surprisingly, Chrome's pinch-to-zoom has this issue and scales up the PDF viewer UI

**Comment by BenQuinlan** [comment] 2019-06-05 16:13
Just wondering if anyone might want to re-visit this issue at some point?

**Comment by haxiomic** [comment] 2019-06-05 16:28
Hey @BenQuinlan, I've just tested this again in FF 67 and now when I pinch zoom the PDF viewer changes the zoom % rather than scaling the UI (this is something that's changed in the PDF viewer rather than this extension). What does it do for you?

**Comment by BenQuinlan** [comment] 2019-06-05 16:32
@haxiomic I've just realized when I pinch zoom with the mouse-pad it works correctly, but I typically use a touchscreen (surfacebook) and that pinch zoom changes the zoom in the entire browser versus the PDF viewer. Not sure if there's a way to change it or not, but thought I'd bring it up.

**Comment by haxiomic** [comment] 2019-06-05 16:38
@BenQuinlan Interesting! When you sue the touch screen are the changes smooth or incremental?

**Comment by BenQuinlan** [comment] 2019-06-05 16:41
@haxiomic The changes are incremental when using the touchscreen on the PDF viewer. On any other non-PDF page, it is smooth as intended.

**Comment by haxiomic** [comment] 2019-06-05 17:09
Ahh ok, I see what's going on – after testing it looks like Firefox now disable extensions on the PDF viewer, so the zoom you're seeing must be the native behaviour. You can check the value of `browser.gesture.pinch.out` (and similar) in about:config to see if it's set to anything other than default

Incidentally, I'll close this issue because we can no longer affect the PDF viewer

**Closed by haxiomic** 2019-06-05 17:09 UTC
